import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

export async function sendGatePassEmail(email, gatePass) {
  try {
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false, // STARTTLS
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS, // Use App Password if 2FA is enabled
      },
      tls: {
        rejectUnauthorized: false,
      },
      logger: true,
      debug: true,
    });

    // ✅ Utility to format date as DD-MM-YYYY
    function formatDate(date) {
      if (!date) return "-";
      const d = new Date(date);
      const day = String(d.getDate()).padStart(2, "0");
      const month = String(d.getMonth() + 1).padStart(2, "0");
      const year = d.getFullYear();
      return `${day}-${month}-${year}`;
    }

    // ✅ Footer (moved inside function)
    const footer = `
      <hr>
      <p style="font-size:0.9em;color:#555;">
        This email was automatically generated by the GatePass System.<br>
        Please do not reply directly to this message.
      </p>
    `;
// ✅ Utility to mask Aadhaar
function maskAadhaar(aadhaar) {
  if (!aadhaar) return "-";
  const clean = aadhaar.replace(/\D/g, "");
  return `XXXX-XXXX-${clean.slice(-4)}`;
}

    // ✅ Main Email HTML
    const html = `
      <h2>Gate Pass Details</h2>
      <p><strong>Gate Pass No:</strong> ${gatePass.gate_pass_no}</p>
      <p><strong>Name:</strong> ${gatePass.name}</p>
      <p><strong>Visitor Type:</strong> ${gatePass.visitor_type || "N/A"}</p>
      <p><strong>Aadhaar:</strong> ${maskAadhaar(gatePass.aadhaar)}</p>
      <p><strong>Address:</strong> ${gatePass.address}</p>
      <p><strong>Generated By:</strong> ${gatePass.generated_by}</p>
      <p><strong>Meet To:</strong> ${gatePass.meet_to}</p>
      <p><strong>Building:</strong> ${gatePass.building}</p>
      <p><strong>Equipment:</strong> ${gatePass.equipment}</p>
      <p><strong>Persons:</strong> ${gatePass.persons}</p>
      <p><strong>Accompanying:</strong> ${gatePass.accompanying_names || "N/A"}</p>
      <p><strong>Date:</strong> ${formatDate(gatePass.visit_date)}</p>
      <p><strong>In Time:</strong> ${gatePass.time_in || "-"}</p>
      <p><strong>Out Time:</strong> ${gatePass.time_out || "-"}</p>
      ${gatePass.building?.toLowerCase() === "plant"
        ? `<p style="color:red;"><strong>Note:</strong> Please visit HSE building for safety induction.</p>`
        : ""}
      ${gatePass.photo
        ? `<img src="${gatePass.photo}" alt="Gate Pass Photo" style="max-width:500px;border:1px solid #ccc;margin-top:10px;">`
        : ""}
      ${footer}
    `;

    // ✅ Handle multiple recipients
    const recipients = email
      .split(",")
      .map((e) => e.trim())
      .filter((e) => e.length > 0);

    if (recipients.length === 0) {
      throw new Error("No valid email addresses provided");
    }

    const info = await transporter.sendMail({
      from: `"Gate Pass System" <${process.env.EMAIL_USER}>`,
      to: recipients,
      subject: `Gate Pass: ${gatePass.gate_pass_no}`,
      html,
    });

    console.log("✅ Email sent successfully:", info.messageId);
    return info;
  } catch (err) {
    console.error("❌ Email sending failed:", err);
    throw err;
  }
}

export default sendGatePassEmail;
